# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: |
      github.event.review.state == 'approved' &&
      github.event.author_association == 'OWNER'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Actions Ecosystem Add Labels
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          labels: Ready To Merge
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Actions Ecosystem Remove Labels
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: Changes Requested

  changes_requested:
    if: |
      github.event.review.state == 'changes_requested' &&
      github.event.author_association == 'OWNER'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Actions Ecosystem Add Labels
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          labels: Changes Requested
          github_token: "${{ secrets.GITHUB_TOKEN }}"
